[phases.build]
cmds = ["npm run build && cp -r .next/static .next/standalone/.next/ && cp -r public .next/standalone/"]

[phases.install]
cacheDirectories = []

[start]
cmd = "node .next/standalone/server.js"
