[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo NODE_ENV=$NODE_ENV && NODE_ENV=production npm run build"]

[start]
cmd = "npm run start"

# Disable all caching
[options]
cacheDirectories = []
